deep/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from django.core.urlresolvers import reverse_lazy

from rest_framework.routers import DefaultRouter

from users.views import *
from deep.views import *
from report.views import *
from entries.views import ExportProgressView, WebsiteInfoView

from users.rest_views import *
from usergroup.rest_views import *
from leads.rest_views import *
from entries.rest_views import *
from deep.api_views import OverviewApiView, ReportsApiView


router = DefaultRouter()
router.register(r'leads', LeadViewSet, base_name='lead')
router.register(r'entries', EntryViewSet, base_name='entry')
router.register(r'entry-templates', EntryTemplateViewSet, base_name='entry-template')
router.register(r'sources', SourceViewSet, base_name='source')
router.register(r'events', EventViewSet, base_name='event')
router.register(r'events2', EventViewSet2, base_name='event2')
router.register(r'users', UserViewSet, base_name='user')
router.register(r'user-groups', UserGroupViewSet, base_name='user-group')
router.register(r'users2', UserViewSet2, base_name='user')
router.register(r'countries', CountryViewSet, base_name='country')
router.register(r'survey-of-surveys', SosViewSet, base_name='country')


urlpatterns = [

    ## ERROR PAGES
    url(r'^404/$', TemplateView.as_view(template_name='404.html')),
    url(r'^500/$', TemplateView.as_view(template_name='500.html')),

    url(r'^$', IndexView.as_view()),
    url(r'^register/$', RegisterView.as_view(), name="register"),
    url(r'^hid-access-token$', HidAccessToken.as_view(), name="hid_access_token"),
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    url(r'^extension/$', ExtensionView.as_view(), name="extension"),

    url(r'^load/countries/$', LoadCountries.as_view()),

    url(r'^dashboard/$', DashboardView.as_view(), name="dashboard"),
    url(r'^export-progress/$', ExportProgressView.as_view(), name="export_progress"),
    url(r'^download-file/$', DownloadFileView.as_view(), name="download_file"),

    url(r'^(?P<event>\d+)/dashboard/$', DashboardView.as_view(), name="dashboard"),
    url(r'^(?P<event>\d+)/leads/', include('leads.urls', namespace='leads')),
    url(r'^(?P<event>\d+)/entries/', include('entries.urls', namespace='entries')),

    url(r'^project/(?P<project_id>\d+)/', include('project.urls', namespace='project')),
    url(r'^usergroup/', include('usergroup.urls', namespace='usergroup')),
    url(r'^custom-admin/', include('custom_admin.urls', namespace='custom_admin')),
    url(r'^report/', include('report.urls', namespace='report')),

    url(r'^user/(?P<user_id>\d+)', UserProfileView.as_view(), name="user_profile"),

    # API for chrome extension
    url(r'user/status/', UserStatusView.as_view(), name="status"),
    url(r'date/', DateExtractorView.as_view(), name="date"),

    url(r'^admin/', admin.site.urls),
    url(r'^api/v1/', include(router.urls)),
    url(r'^api/v2/', include('entries.api_urls', namespace='api_entries')),
    url(r'^api/v2/', include('leads.api_urls', namespace='api_leads')),
    url(r'^api/v2/', include('report.api_urls', namespace='api_report')),

    url(r'api/v2/website-info/',
        WebsiteInfoView.as_view(), name='website_info'),

    url(r'^api/v2/dashboard/overview/$', OverviewApiView.as_view()),
    url(r'^api/v2/dashboard/reports/$', ReportsApiView.as_view()),

    url(r'^password/reset/$',
        auth_views.password_reset,
        {'post_reset_redirect': reverse_lazy('password_rest_done')},
        name="password_reset"),

    url(r'^password/reset/done/$',
        auth_views.password_reset_done,
        name="password_rest_done"),

    url(r'^password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        auth_views.password_reset_confirm,
        {'post_reset_redirect': reverse_lazy('password_reset_complete')},
        name="password_reset_confirm"),

    url(r'^password/done/$',
        auth_views.password_reset_complete,
        name="password_reset_complete"),

    url(r'^password/change/$',
        auth_views.password_change,
        name="password_change"),

    url(r'^password/change/done/$',
        auth_views.password_change,
        name="password_change_done"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

leads/urls.py
from django.conf.urls import url, include
from leads import views


urlpatterns = [
    url(r'^$', views.LeadsView.as_view(), name="leads"),
    url(r'^add/$', views.AddLead.as_view(), name='add'),
    url(r'^add-sos/(?P<lead_id>\d+)/$', views.AddSoS.as_view(), name='add_sos'),
    url(r'^edit-sos/(?P<lead_id>\d+)/(?P<sos_id>\d+)/$', views.AddSoS.as_view(), name='edit_sos'),
    url(r'^edit/(?P<id>\d+)/$', views.AddLead.as_view(), name='edit'),
    url(r'^mark_processed/$', views.MarkProcessed.as_view(), name='mark_processed'),
    url(r'^delete/$', views.DeleteLead.as_view(), name='delete'),
    url(r'^delete-sos/$', views.DeleteSoS.as_view(), name='delete_sos'),
    url(r'^sos/$', views.SoSView.as_view(), name="sos"),

    url(r'^exportsosxls/$', views.ExportSosXls.as_view(), name="exportsosxls"),
]

leads/models.py
from django.db import models
from django.contrib.auth.models import User
# from django.db.models.signals import pre_delete
from django.db.models import Q
from django.core.files import File

from datetime import datetime
import random
import string


class Country(models.Model):
    reference_country = models.ForeignKey('leads.Country', null=True,
                                          default=None)

    code = models.CharField(max_length=5, primary_key=True)
    name = models.CharField(max_length=70)

    key_figures = models.TextField(default='{}')
    media_sources = models.TextField(default='{}')
    regions = models.TextField(default='{}')

    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name_plural = 'countries'

    @staticmethod
    def get_unique_code():
        code = ''
        while True:
            code = ''.join(random.choice(
                string.ascii_uppercase + string.digits) for _ in range(5))
            if Country.objects.filter(code=code).count() == 0:
                break

        return code


class Event(models.Model):
    """ Event Model

    Contains leads and their entries.
    """

    STATUSES = (
        (0, 'Global monitoring'),
        (1, 'Active crisis'),
    )

    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)

    created_at = models.DateTimeField(auto_now_add=True, null=True)
    modified_at = models.DateTimeField(auto_now=True, null=True)

    countries = models.ManyToManyField(Country, blank=True)
    disaster_type = models.ForeignKey('report.DisasterType', null=True,
                                      blank=True, default=None)
    entry_template = models.ForeignKey('entries.EntryTemplate', null=True,
                                       blank=True, default=None)

    admins = models.ManyToManyField(User, blank=True,
                                    related_name="events_owned")
    members = models.ManyToManyField(User, blank=True)

    # TO DELETE
    assigned_to = models.ForeignKey(User, null=True, blank=True, default=None,
                                    related_name="event_donot_use",
                                    verbose_name="DO NOT USE")

    assignee = models.ManyToManyField(User, blank=True,
                                      related_name="assigned_to")

    glide_number = models.CharField(max_length=100, null=True,
                                    blank=True, default=None)
    spill_over = models.ForeignKey('Event', null=True,
                                   blank=True, default=None)

    start_date = models.DateField(default=datetime.now)
    end_date = models.DateField(null=True, blank=True, default=None)

    status = models.IntegerField(default=1, choices=STATUSES)

    def get_num_entries(self):
        from entries.models import Entry
        return Entry.objects.filter(lead__event__pk=self.pk).count()

    def get_num_members(self):
        return User.objects.filter(Q(usergroup__projects__pk=self.pk) |
                                   Q(groups_owned__pk=self.pk) |
                                   Q(event__pk=self.pk) |
                                   Q(events_owned__pk=self.pk)).distinct().count()

    def is_acaps(self):
        from usergroup.models import UserGroup
        return UserGroup.objects.filter(acaps=True,
                                        projects__pk=self.pk).count() > 0

    def get_admins(self):
        return User.objects.filter(events_owned__pk=self.pk)
        # return User.objects.filter(
        #     Q(events_owned__pk=self.pk) |
        #     Q(groups_owned__projects__pk=self.pk)
        # ).distinct()

    @staticmethod
    def get_events_for(user):
        if user.is_superuser:
            return Event.objects.all()

        return Event.objects.filter(
            Q(members=user) | Q(admins=user) | Q(usergroup__members=user)
        ).distinct()

    def allow(self, user):
        return user.is_superuser or \
            user in self.members.all() or user in self.admins.all() or \
            user in User.objects.filter(usergroup__projects=self)

    def __str__(self):
        return self.name


class Source(models.Model):
    """ Source Model

    Sources are available lead sources.
    """

    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Lead(models.Model):
    """ Lead Model
    """

    # Confidentiality choices, currently including public and confidential.
    UNPROTECTED = 'UNP'
    PROTECTED = 'PRO'
    RESTRICTED = 'RES'
    CONFIDENTIAL = 'CON'

    CONFIDENTIALITIES = (
        (UNPROTECTED, 'Unprotected'),
        (PROTECTED, 'Protected'),
        (RESTRICTED, 'Restricted'),
        (CONFIDENTIAL, 'Confidential'),
    )

    # Status of a lead that can be pending, processed or deleted.
    PENDING = 'PEN'
    PROCESSED = 'PRO'
    DELETED = 'DEL'

    STATUSES = (
        (PENDING, 'Pending'),
        (PROCESSED, 'Processed'),
        (DELETED, 'Deleted'),
    )

    # Lead types.
    URL_LEAD = 'URL'
    MANUAL_LEAD = 'MAN'
    ATTACHMENT_LEAD = 'ATT'
    SOS_LEAD = 'SOS'

    LEAD_TYPES = (
        (URL_LEAD, 'Url'),
        (MANUAL_LEAD, 'Manual'),
        (ATTACHMENT_LEAD, 'Attachments'),
        (SOS_LEAD, "Survey of surveys"),
    )

    # Lead attributes.
    name = models.CharField(max_length=250)
    event = models.ForeignKey(Event, default=None, null=True)
    source = models.ForeignKey(Source, null=True, blank=True)
    source_name = models.CharField(max_length=250, default=None,
                                   null=True, blank=True)
    assigned_to = models.ForeignKey(User, null=True, blank=True,
                                    related_name='assigned_leads')
    published_at = models.DateField(null=True, blank=True)

    confidentiality = models.CharField(max_length=3,
                                       choices=CONFIDENTIALITIES,
                                       default=UNPROTECTED)
    status = models.CharField(max_length=3,
                              choices=STATUSES,
                              default=PENDING)
    lead_type = models.CharField(max_length=3,
                                 choices=LEAD_TYPES,
                                 default=MANUAL_LEAD)

    description = models.TextField(blank=True, null=True)
    url = models.TextField(blank=True, null=True)
    website = models.CharField(max_length=255, blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User)

    def __str__(self):
        return self.name

    def clone_to(self, event):
        if event.pk == self.event:
            return self

        new_lead = Lead(event=event)
        new_lead.name = self.name
        new_lead.source_name = self.source_name
        new_lead.assigned_to = self.assigned_to
        new_lead.published_at = self.published_at
        new_lead.confidentiality = self.confidentiality
        new_lead.status = self.status
        new_lead.lead_type = self.lead_type
        new_lead.description = self.description
        new_lead.url = self.url
        new_lead.website = self.website
        new_lead.created_by = self.created_by
        new_lead.save()

        if hasattr(self, 'attachment'):
            att = Attachment(lead=new_lead)
            att.image = File(self.attachament.upload,
                             self.attachments.upload.name)
            att.save()

        if hasattr(self, 'simplifiedlead'):
            SimplifiedLead(lead=new_lead,
                           text=self.simplifiedlead.text).save()

        for image in LeadImage.objects.filter(lead=self):
            img = LeadImage(lead=new_lead)
            img.image = File(image.image, image.image.name)
            img.save()

        return new_lead


class Attachment(models.Model):
    """ Attachment model

    It represents an uploaded file and belongs to a lead.
    """

    lead = models.OneToOneField(Lead)
    upload = models.FileField(upload_to='attachments/%Y/%m/')

    def __str__(self):
        return self.lead.name + ' - ' + self.upload.name


class SimplifiedLead(models.Model):
    lead = models.OneToOneField(Lead)
    # simplified text
    text = models.TextField()

    def __str__(self):
        return self.lead.name


class LeadImage(models.Model):
    lead = models.ForeignKey(Lead)
    image = models.FileField(Lead, upload_to='leadimages/')

    def __str__(self):
        return self.lead.name

# @receiver(pre_delete, sender=Attachment)
# def _attachment_delete(sender, instance, **kwargs):
#     instance.upload.delete(False)


"""Survey of survey """


class ProximityToSource(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Proximity to Sources"


class UnitOfAnalysis(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Units of Analysis"


class UnitOfReporting(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Units of Reporting"


class DataCollectionTechnique(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Data Collection Techniques"


class SamplingType(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Sampling Types"


class SectorQuantification(models.Model):
    name = models.CharField(max_length=100)
    is_default = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class SectorAnalyticalValue(models.Model):

leads/templates/leads/add-lead.html
{% extends 'base.html' %}
{% load watchful_url %}

{% block title %}
DEEP | {% if lead %}Edit{% else %}Add{% endif %} Lead
{% endblock %}

{% block head %}
<link href="{% watchful_static_url 'css/add-lead.css' %}" type="text/css" rel="stylesheet">
<link href="{% watchful_static_url 'css/selectize.css' %}" type="text/css" rel="stylesheet">
<link href="{% watchful_static_url 'css/dropzone.css' %}" type="text/css" rel="stylesheet">
<script type="text/javascript" src="{% watchful_static_url 'js/common/selectize.js' %}"></script>
<script type="text/javascript" src="{% watchful_static_url 'js/common/dropzone.js' %}"></script>
<script type="text/javascript" src="{% watchful_static_url 'js/common/utils.js' %}"></script>
<script type="text/javascript" src="{% watchful_static_url 'js/leads/add-lead.js' %}"></script>


{% endblock %}

{% block body %}

{% include 'navbar.html' %}

<section id="main">
    <h2>{% if lead %}Edit{% else %}Add{% endif %} Lead</h2>
    <form id="attachment-dropzone" class="dropzone" method="post">
        {% csrf_token %}
        <label>Name:</label>
        <input type="text" name="name" placeholder="Enter a descriptive name" {%if lead%}value="{{lead.name}}" {%endif%} required>
        <label>Source:</label>
        <!--select id="source" name="source" placeholder="Select source type">
            <option value="">Select source type</option>
            {% for s in sources %}
            <option value="{{s.pk}}" {% if lead and lead.source == s %} selected {% endif %}>{{s}}</option>
            {% endfor %}
        </select-->
        <input type="text" name="source" placeholder="Enter source" {% if lead %}value="{{lead.source_name}}"{% endif %}>
        <div {%if lead %} {% else %} style="display: none;"{% endif %}>
            <label>Crisis:</label>
            <select name="event" id="crisis-lead" placeholder="Select crisis">
                <option value="">Select Crisis</option>
                {% for e in events %}
                <option value="{{e.pk}}" {% if e.pk == event.pk %}selected{% endif %}>{{e.name}}</option>
                {% endfor %}
            </select>
            <!-- <input type="text" name="crisis-lead" placeholder="Enter crisis" {% if lead %}value="{{e.pk}}"{% endif %}> -->
        </div>
        <label>Confidentiality:</label>
        <select id="confidentiality" name="confidentiality">
            {% for c in confidentialities %}
            <option value="{{c.0}}" {% if lead and lead.confidentiality == c.0 %} selected {% endif %}>{{c.1}}</option>
            {% endfor %}
        </select>
        <label>Assign to:</label>
        <select id="assigned-to" name="assigned-to" placeholder="Select user">
            <option value="">Select user</option>
            {% for u in users %}
            <option value="{{u.pk}}" {% if lead and lead.assigned_to == u %} selected {% endif %}}>
            {{u.first_name}} {{u.last_name}}
            </option>
            {% endfor %}
        </select>
        <label>Publication date:</label>
        <div style="position:relative;">
            <input type="date" name="publish-date" class="publish-date" placeholder="yyyy-mm-dd" {% if lead %}value="{{lead.published_at|date:"Y-m-d"}}"{% endif %}>
            <input type="text" class="date-picker" data-alt=".publish-date" {% if lead %}value="{{lead.published_at|date:"d-m-Y"}}"{% endif %}>
        </div>
        <div id="radio-btn-container">
            <label>Type:</label>
            <label><input type="radio" name="lead-type" value="website" {% if not lead or lead.lead_type == 'URL' %} checked {% endif %}>Website</label>
            <label><input type="radio" name="lead-type" value="manual" {% if lead and lead.lead_type == 'MAN' %} checked {% endif %}>Manual Entry</label>
            <label><input type="radio" name="lead-type" value="attachment" {% if lead and lead.lead_type == 'ATT' %} checked {% endif %}>Attachment</label>
        </div>
        <div id="description-row">
            <label>Description:</label><br>
            <textarea name="description" placeholder="Enter description" rows="16">{% if lead %}{{lead.description}}{% endif %}</textarea>
        </div>
        <div id="url-row">
            <label>URL</label>
            <input type="text" name="url" placeholder="Enter url" {% if lead %}value="{{lead.url}}"{% endif %}>
        </div>
        <div id="website-row">
            <label>Website</label>
            <input type="text" name="website" placeholder="Enter website" {% if lead %}value="{{lead.website}}"{% endif %}>
        </div>
        <div id="attachment-row">
            <label>
                Attachment:
                {% if lead and lead.attachment %}<br>
                <a href="{{lead.attachment.upload.url}}">{{lead.attachment.upload.name}}</a>
                <br>Upload new file to replace.
                {% endif %}
            </label>
            <div class="dropzone-container">
                <div class="dz-message"> Click or Drop file here </div>
                <div class="dropzone-previews"></div>
            </div>
        </div>
        <div class="actions">
            <!--button class="btn btn-default" name="post" value="save-and-another">Save and add another</button-->
            <a href="{% url 'leads:leads' event.pk %}" onclick="return confirm('All changes will be discarded. Are you sure?');" id="cancel-btn" class="btn btn-default">Cancel</a>
            <button class="submit-btn" type="submit">Submit</button>
            <button name="add-entry" class="submit-btn" type="submit">Submit and Add Entry</button>
        </div>
    </form>
</section>

<script>
var url;
{% if lead %}
url = "{% url 'leads:edit' event=event.pk id=lead.pk %}";
{% else %}
url = "{% url 'leads:add' event=event.pk %}";
{% endif %}

Dropzone.options.attachmentDropzone = {
    {% if lead %}
    url: url,
    {% else %}
    url: url,
    {% endif %}
    autoProcessQueue: false,
    uploadMultiple: false,
    addRemoveLinks: true,
    parallelUploads: 100,
    maxFiles: 1,
    previewsContainer: ".dropzone-previews",
    clickable: ".dropzone-container",

    init: function() {
        // On maximum file succedded, delete files to replace by new one.
        this.on("maxfilesexceeded", function(file) {
            this.removeAllFiles();
            this.addFile(file);
        });

        var dz = this;
        $("button[type=submit]").on("click", function(e) {
            // if (!confirm("Are you sure you want to save these changes?")) {
            //    e.preventDefault();
            //    e.stopPropagation();
            //    return;
            // }
            var leadtype = $("input[name='lead-type']:checked").val();
            if (leadtype == "attachment" && dz.getQueuedFiles().length > 0) {
                e.preventDefault();
                e.stopPropagation();
                dz.processQueue();
            }
        });

        // for multiple: sendingmultiple
        this.on("sending", function() {
            $(".submit-btn").prop("disabled", true);
        });

        // for multiple, successmultiple
        this.on("success", function(files, response) {
            if (response.url) {
                window.location.href = response.url;
            } else {
                window.location.href = url;
            }
        });

        // for multiple, errormultiple
        this.on("error", function(files, response) {
            // TODO: Show error.
            $(".submit-btn").prop("disabled", false);
        });
    },
};
</script>

{% endblock %}

leads/templates/leads/leads.html
{% extends 'base.html' %}
{% load watchful_url %}

{% block title %}
DEEP | Leads
{% endblock %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% watchful_static_url 'css/datatables.min.css' %}"/>
<link rel="stylesheet" type="text/css" href="{% watchful_static_url 'css/selectize.css' %}"/>
<link href="{% watchful_static_url 'css/modal.css' %}" type="text/css" rel="stylesheet">
<link href="{% watchful_static_url 'css/leads.css' %}" type="text/css" rel="stylesheet">

<script>
    var currentEvent = {% if event %}{{ event.pk }}{% else %}null{% endif %};
    var postUrl = "{% url 'leads:add' event=0 %}";
    var isAcaps = {% if event.is_acaps %}true{% else %}false{% endif %};
</script>

<script type="text/javascript" src="{% watchful_static_url 'js/common/datatables.min.js' %}"></script>
<script type="text/javascript" src="{% watchful_static_url 'js/common/selectize.js' %}"></script>
<script type="text/javascript" src="{% watchful_static_url 'js/common/utils.js' %}"></script>
<script type="text/javascript" src="{% watchful_static_url 'js/common/modal.js' %}"></script>
<script type="text/javascript" src="{% watchful_static_url 'js/leads/leads.js' %}"></script>
{% endblock %}

{% block body %}

{% include 'navbar.html' %}

<main>
    {% if event %}
    <a id="add-lead-btn" href="{% url 'leads:add' event=event.pk %}" ><i class="fa fa-plus"></i>Add new lead</a>
    {% else %}
    <a id="add-lead-btn" style="visiblity: hidden;"><i class="fa fa-plus"></i>Add new lead</a>
    {% endif %}
    <div id="filters">
        <label>Apply filter:</label>
        <select id="assigned-to-filter" placeholder="Assigned to">
            <option value="">Assigned to</option>
        </select>
        <select id="date-created-filter" placeholder="Date Created">
            <option value="">Date Created</option>
            <option value="today">Today</option>
            <option value="yesterday">Yesterday</option>
            <option value="last-seven-days">Last 7 days</option>
            <option value="this-week">This week</option>
            <option value="last-thirty-days">Last 30 days</option>
            <option value="this-month">This month</option>
            <option value="range">Range</option>
        </select>
        <select id="date-published-filter" placeholder="Date Published">
            <option value="">Date Published</option>
            <option value="today">Today</option>
            <option value="yesterday">Yesterday</option>
            <option value="last-seven-days">Last 7 days</option>
            <option value="this-week">This week</option>
            <option value="last-thirty-days">Last 30 days</option>
            <option value="this-month">This month</option>
            <option value="range">Range</option>
        </select>
        <select id="confidentiality-filter" placeholder="Confidentiality">
            <option value="">Confidentiality</option>
            <option value="Unprotected">Unprotected</option>
            <option value="Protected">Protected</option>
            <option value="Restricted">Restricted</option>
            <option value="Confidential">Confidential</option>
        </select>
        <select id="status-filter" placeholder="Status">
            <option value="">Status</option>
            <option value="Pending">Pending</option>
            <option value="Processed">Processed</option>
        </select>
    </div>
    <div id="leads-table-wrapper">
        <table id="leads-table" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>Created on</th>
                    <th>Created by</th>
                    <th>Assigned to</th>
                    <th></th>
                    <th>Name</th>
                    <th>Published</th>
                    <th>Confidentiality</th>
                    <th>Source</th>
                    <th>No. of Entries</th>
                    <th>Status</th>
                    <th>Actions</th>
                </tr>
            </thead>
        </table>
    </div>
</main>
<div id="drag-overlay" hidden>
    <div id="border">
        Drop the file here to add a lead from attachment
    </div>
</div>

<form id="process-form" method="post" action="{% url 'leads:mark_processed' event=0 %}" hidden>
    {% csrf_token %}
    <input id="process-id" name="id" type="text">
    <input id="process-status" name="status" type="text">
</form>
<form id="delete-form" method="post" action="{% url 'leads:delete' event=0 %}" hidden>
    {% csrf_token %}
    <input id="delete-id" name="id" type="text">
</form>

<div class="modal-container" hidden>
    <div id="date-range-input" class="modal" hidden>
        <header>
            <h3 class="modal-title">Enter date range</h3>
        </header>
        <div class="input-container">
            <label>start date:</label>
            <input type="date" id="start-date" class="form-control">
            <input type="text" class="date-picker" data-alt="#start-date">
        </div>
        <div class="input-container">
            <label>end date:</label>
            <input type="date" id="end-date" class="form-control">
            <input type="text" class="date-picker" data-alt="#end-date">
        </div>
        <div class="action-buttons">
            <button id="cancel-btn" class="cancel" data-action="dismiss"><i class="fa fa-times"></i>Cancel</button>
            <button id="ok-btn" class="success" data-action="proceed"><i class="fa fa-check"></i>Ok</button>
        </div>
    </div>
    <div id="add-lead-modal" class="modal" hidden>
        <header>
            <h3 class="modal-title">Add Lead</h3>
        </header>
        <form id="add-lead-form">
            {% csrf_token %}
            <div class="input-container">
                <label>Name</label>
                <input type="text" name="name" placeholder="Enter a descriptive name" required>
            </div>
            <div class="input-container">
                <label>Source</label>
                <input id="source" name="source" placeholder="Select source type">
            </div>
            <div class="select-container">
                <label>Confidentiality</label>
                <select id="confidentiality" name="confidentiality">
                    {% for c in confidentialities %}
                    <option value="{{c.0}}">{{c.1}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="select-container">
                <label>Assign to</label>
                <select id="assigned-to" name="assigned-to" placeholder="Select user">
                    <option value="">Select user</option>
                    {% for u in users %}
                    <option value="{{u.pk}}">{{u.first_name}} {{u.last_name}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="input-container">
                <label>Published at</label>
                <input type="date" name="publish-date" placeholder="yyyy-mm-dd">
                <input type="text" class="date-picker" data-alt="[name='publish-date']">
            </div>
            <div class="input-container attachment-row">
                <label>Attachments</label>
                <div id="attachments-list"></div>
            </div>
            <div class="textarea-container manual-row">
                <label>Description</label>
                <textarea id="manual-text"></textarea>
            </div>
            <input type="submit" style="width:0; height:0; opacity:0;">
        </form>
        <div class="action-buttons">
            <button id="cancel-btn" class="cancel" data-action="dismiss"><i class="fa fa-times"></i>Cancel</button>
            <button id="submit-btn" class="success" data-action="submit" data-persist="true"><i class="fa fa-check"></i>Submit</button>
        </div>
    </div>
</div>
{% endblock %}