custom_admin/urls.py
from django.conf.urls import url, include
from custom_admin import views


urlpatterns = [
    url(r'^project-panel/$', views.ProjectPanelView.as_view(), name="project_panel"),
    url(r'^country-management/$', views.CountryManagementView.as_view(), name="country_management"),
    url(r'^entry-template/(?P<template_id>\d+)/$', views.EntryTemplateView.as_view(), name="entry_template"),
]

deep/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from django.core.urlresolvers import reverse_lazy

from rest_framework.routers import DefaultRouter

from users.views import *
from deep.views import *
from report.views import *
from entries.views import ExportProgressView, WebsiteInfoView

from users.rest_views import *
from usergroup.rest_views import *
from leads.rest_views import *
from entries.rest_views import *
from deep.api_views import OverviewApiView, ReportsApiView


router = DefaultRouter()
router.register(r'leads', LeadViewSet, base_name='lead')
router.register(r'entries', EntryViewSet, base_name='entry')
router.register(r'entry-templates', EntryTemplateViewSet, base_name='entry-template')
router.register(r'sources', SourceViewSet, base_name='source')
router.register(r'events', EventViewSet, base_name='event')
router.register(r'events2', EventViewSet2, base_name='event2')
router.register(r'users', UserViewSet, base_name='user')
router.register(r'user-groups', UserGroupViewSet, base_name='user-group')
router.register(r'users2', UserViewSet2, base_name='user')
router.register(r'countries', CountryViewSet, base_name='country')
router.register(r'survey-of-surveys', SosViewSet, base_name='country')


urlpatterns = [

    ## ERROR PAGES
    url(r'^404/$', TemplateView.as_view(template_name='404.html')),
    url(r'^500/$', TemplateView.as_view(template_name='500.html')),

    url(r'^$', IndexView.as_view()),
    url(r'^register/$', RegisterView.as_view(), name="register"),
    url(r'^hid-access-token$', HidAccessToken.as_view(), name="hid_access_token"),
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    url(r'^extension/$', ExtensionView.as_view(), name="extension"),

    url(r'^load/countries/$', LoadCountries.as_view()),

    url(r'^dashboard/$', DashboardView.as_view(), name="dashboard"),
    url(r'^export-progress/$', ExportProgressView.as_view(), name="export_progress"),
    url(r'^download-file/$', DownloadFileView.as_view(), name="download_file"),

    url(r'^(?P<event>\d+)/dashboard/$', DashboardView.as_view(), name="dashboard"),
    url(r'^(?P<event>\d+)/leads/', include('leads.urls', namespace='leads')),
    url(r'^(?P<event>\d+)/entries/', include('entries.urls', namespace='entries')),

    url(r'^project/(?P<project_id>\d+)/', include('project.urls', namespace='project')),
    url(r'^usergroup/', include('usergroup.urls', namespace='usergroup')),
    url(r'^custom-admin/', include('custom_admin.urls', namespace='custom_admin')),
    url(r'^report/', include('report.urls', namespace='report')),

    url(r'^user/(?P<user_id>\d+)', UserProfileView.as_view(), name="user_profile"),

    # API for chrome extension
    url(r'user/status/', UserStatusView.as_view(), name="status"),
    url(r'date/', DateExtractorView.as_view(), name="date"),

    url(r'^admin/', admin.site.urls),
    url(r'^api/v1/', include(router.urls)),
    url(r'^api/v2/', include('entries.api_urls', namespace='api_entries')),
    url(r'^api/v2/', include('leads.api_urls', namespace='api_leads')),
    url(r'^api/v2/', include('report.api_urls', namespace='api_report')),

    url(r'api/v2/website-info/',
        WebsiteInfoView.as_view(), name='website_info'),

    url(r'^api/v2/dashboard/overview/$', OverviewApiView.as_view()),
    url(r'^api/v2/dashboard/reports/$', ReportsApiView.as_view()),

    url(r'^password/reset/$',
        auth_views.password_reset,
        {'post_reset_redirect': reverse_lazy('password_rest_done')},
        name="password_reset"),

    url(r'^password/reset/done/$',
        auth_views.password_reset_done,
        name="password_rest_done"),

    url(r'^password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        auth_views.password_reset_confirm,
        {'post_reset_redirect': reverse_lazy('password_reset_complete')},
        name="password_reset_confirm"),

    url(r'^password/done/$',
        auth_views.password_reset_complete,
        name="password_reset_complete"),

    url(r'^password/change/$',
        auth_views.password_change,
        name="password_change"),

    url(r'^password/change/done/$',
        auth_views.password_change,
        name="password_change_done"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.conf.urls import url, include
from project.views import *


urlpatterns = [
    url(r'^details/$', ProjectDetailsView.as_view(), name="project_details"),
    url(r'^geo-area/$', GeoAreaView.as_view(), name="geo_area"),
    url(r'^analysis-framework/$', AnalysisFrameworkView.as_view(), name="analysis_framework"),
]

entries/models.py
from django.db import models
from django.contrib.auth.models import User
# from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver
from django.utils import timezone

from leads.models import *
from entries.load_geo_areas import load_geo_areas

import json


class AdminLevel(models.Model):
    level = models.IntegerField()
    country = models.ForeignKey(Country)
    name = models.CharField(max_length=70)
    property_name = models.CharField(max_length=70)
    property_pcode = models.CharField(max_length=50, default="", blank=True)
    geojson = models.FileField(upload_to='adminlevels/', default=None, blank=True, null=True)
    geo_areas = models.TextField(default='[]')

    def __str__(self):
        return self.name + ", " + str(self.country)

    class Meta:
        ordering = ['country', 'level']
        unique_together = ('country', 'level')

    def save(self, *args, **kwargs):
        self.geo_areas = json.dumps(load_geo_areas(self))
        super(AdminLevel, self).save(*args, **kwargs)


# @receiver(pre_delete, sender=AdminLevel)
# def _admin_level_delete(sender, instance, **kwargs):
#     instance.geojson.delete(False)


class AdminLevelSelection(models.Model):
    admin_level = models.ForeignKey(AdminLevel)
    name = models.CharField(max_length=70)
    pcode = models.CharField(max_length=50, default="", blank=True)

    def __str__(self):
        if self.pcode == "":
            return self.name + ", " + str(self.admin_level)
        else:
            return self.name + " (" + self.pcode + ")" + ", " + str(self.admin_level)

    def get_keyword(self):
        # "{{self.admin_level.country.code}}:{{self.admin_level.level|add:'-1'}}:{{self.name}}"
        if self.pcode != '':
            return str(self.admin_level.country.code) + ":" + str(self.admin_level.level) + ":" + str(self.name) + ":" + str(self.pcode)
        return str(self.admin_level.country.code) + ":" + str(self.admin_level.level) + ":" + str(self.name)


class Reliability(models.Model):
    name = models.CharField(max_length=100)
    level = models.IntegerField()
    is_default = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Reliabilities'
        ordering = ['level']


class Severity(models.Model):
    name = models.CharField(max_length=100)
    level = models.IntegerField()
    is_default = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Severities'
        ordering = ['level']


class AffectedGroup(models.Model):
    name = models.CharField(max_length=150)
    parent = models.ForeignKey("entries.AffectedGroup", blank=True, default=None, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Affected Groups"


class VulnerableGroup(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Vulnerable Groups"


class SpecificNeedsGroup(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Specific Needs Groups"


class InformationPillar(models.Model):
    name = models.CharField(max_length=150)
    contains_sectors = models.BooleanField(default=False)

    tooltip = models.TextField(default='', blank=True)

    background_color = models.CharField(max_length=20, default="#fbe8db")
    active_background_color = models.CharField(max_length=20, default="#ea7120")

    PEOPLE_IN_NEED = "PIN"
    HUMANITARIAN_ACCESS = "HAC"
    HUMANITARIAN_PROFILE = "HPR"
    CASUALTIES = "CAS"
    KEY_EVENTS = "KEY"

    APPEAR_IN = (
        (PEOPLE_IN_NEED, "People in need"),
        (HUMANITARIAN_ACCESS, "Humanitarian access"),
        (HUMANITARIAN_PROFILE, "Humanitarian profile"),
        (CASUALTIES, "Casualties"),
        (KEY_EVENTS, "Key events"),
    )

    appear_in = models.CharField(max_length=3, choices=APPEAR_IN,
                                 blank=True, null=True, default=None)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Information Pillars"


class InformationSubpillar(models.Model):
    name = models.CharField(max_length=150)
    pillar = models.ForeignKey(InformationPillar)

    tooltip = models.TextField(default='', blank=True)

    PEOPLE_IN_NEED = "PIN"
    HUMANITARIAN_ACCESS = "HAC"
    HUMANITARIAN_PROFILE = "HPR"
    CASUALTIES = "CAS"
    KEY_EVENTS = "KEY"

    APPEAR_IN = (
        (PEOPLE_IN_NEED, "People in need"),
        (HUMANITARIAN_ACCESS, "Humanitarian access"),
        (HUMANITARIAN_PROFILE, "Humanitarian profile"),
        (CASUALTIES, "Casualties"),
        (KEY_EVENTS, "Key events"),
    )

    appear_in = models.CharField(max_length=3, choices=APPEAR_IN,
                                 blank=True, null=True, default=None)

    def __str__(self):
        return self.name


class Sector(models.Model):
    name = models.CharField(max_length=150)
    icon = models.FileField(upload_to="sector-icons/", null=True, blank=True, default=None)

    def __str__(self):
        return self.name


# @receiver(pre_delete, sender=Sector)
# def _sector_delete(sender, instance, **kwargs):
#     instance.icon.delete(False)


class Subsector(models.Model):
    sector = models.ForeignKey(Sector)
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name


class Entry(models.Model):
    modified_at = models.DateTimeField(auto_now=True)
    modified_by = models.ForeignKey(User, default=None, null=True, blank=True)
    created_at = models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey(User, default=None, null=True, blank=True, related_name='entries_created')
    lead = models.ForeignKey(Lead)

    # Following is for entries entered using template
    template = models.ForeignKey('entries.EntryTemplate', default=None,  null=True, blank=True)

    def __str__(self):
        return str(self.lead)

    class Meta:
        verbose_name_plural = 'Entries'


class EntryInformation(models.Model):
    entry = models.ForeignKey(Entry)
    excerpt = models.TextField(blank=True)
    image = models.TextField(blank=True, default='')

    # Following data is for old data type
    date = models.DateField(blank=True, default=None, null=True)
    reliability = models.ForeignKey(Reliability, default=None, null=True)
    severity = models.ForeignKey(Severity, default=None, null=True)
    number = models.IntegerField(blank=True, default=None, null=True)
    vulnerable_groups = models.ManyToManyField(VulnerableGroup, blank=True)
    specific_needs_groups = models.ManyToManyField(SpecificNeedsGroup, blank=True)
    affected_groups = models.ManyToManyField(AffectedGroup, blank=True)
    map_selections = models.ManyToManyField(AdminLevelSelection, blank=True)
    bob = models.BooleanField(default=False) # best of bullshits

    # Following is for entries entered using template
    elements = models.TextField(default='[]')

    def __str__(self):
        return self.excerpt


class InformationAttribute(models.Model):
    information = models.ForeignKey(EntryInformation)
    subpillar = models.ForeignKey(InformationSubpillar)
    sector = models.ForeignKey(Sector, blank=True, null=True, default=None)

    # TO DELETE
    subsector = models.ForeignKey(Subsector, blank=True, null=True, default=None, related_name='informationattribute_donot_use', verbose_name='DO NOT USE')

    subsectors = models.ManyToManyField(Subsector, blank=True)

    def __str__(self):
        return str(self.subpillar) + "/" + str(self.sector) + "/" + str(self.subsector)


class EntryTemplate(models.Model):
    name = models.CharField(max_length=150)
    elements = models.TextField(default='[]')
    snapshot_pageone = models.TextField(default=None, null=True)
    snapshot_pagetwo = models.TextField(default=None, null=True)
    created_by = models.ForeignKey(User)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def get_admins(self):
        return User.objects.filter(
            events_owned__entry_template=self
        ).distinct()


class ExportToken(models.Model):
    token = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    data = models.TextField(blank=True)

    def __str__(self):
        return self.name

project/models.py
from django.db import models

project/templates/project/analysis-framework.html
{% extends 'base.html' %}
{% load watchful_url %}

{% block title %}
DEEP | Analysis Framework
{% endblock %}

{% block head %}

<link rel="stylesheet" type="text/css" href="{% watchful_static_url 'css/selectize.css' %}" />
<link rel="stylesheet" href="{% watchful_static_url 'css/modal.css' %}" >
<link rel="stylesheet" type="text/css" href="{% watchful_static_url 'css/analysis-framework.css' %}" />

<script src="{% watchful_static_url 'js/common/modal.js' %}"></script>
<script type="text/javascript" src="{% watchful_static_url 'js/common/selectize.js' %}"></script>
<script type="text/javascript" src="{% watchful_static_url 'js/common/utils.js' %}"></script>
<script type="text/javascript" src="{% watchful_static_url 'js/project/analysis-framework.js' %}"></script>

<script>
const num_entries = {{ num_entries }};
const num_shared_projects = {{ num_shared_projects }};
const editUrl = "{% url 'custom_admin:entry_template' project.entry_template.pk %}?redirect={{ request.path|urlencode }}";
</script>

{% endblock %}

{% block body %}

{% include 'simplified-navbar.html' with page_title="Project Management Panel" %}

<aside>
    <header>
        <h2>Related analysis frameworks</h2>
        <div class="search-block">
            <i class="fa fa-search"></i>
            <input id="search-templates" type="search" name="project-search" placeholder="Search templates">
        </div>
    </header>
    <div id="related-project-list">
        {% for p in projects %}
        <div class="project" data-pk="{{ p.pk }}" data-name="{{ p.name }}" data-template="{{ p.entry_template.name }}" data-image-one="{{ p.entry_template.snapshot_pageone }}" data-image-two="{{ p.entry_template.snapshot_pagetwo }}">
            <div class="details">
                <div class="project-name">{{ p.name }}</div>
                <div class="template-name">{{ p.entry_template.name }}</div>
            </div>
            {% if p != project and p.entry_template %}
            <a>View</a>
            {% endif %}
        </div>
        {% endfor %}
    </div>
</aside>
<main>
    <header>
        <a href="{% url 'project:project_details' project_id %}">1. Project details</a>
        <a href="{% url 'project:geo_area' project_id %}">2. Geo area</a>
        <a class="active">3. Analysis framework</a>
    </header>
    <div id="template-form-container">
        <form method="post">
            {% csrf_token %}
            <header>
                <h2>Edit template</h2>
                <div class="action-buttons">
                    <!-- <button id="save-and-edit-template-btn" name="save-and-edit"><i class="fa fa-external-link"></i>Save &amp; edit template</button> -->
                    <button id="save-and-finish-btn" name="save-and-finish"><i class="fa fa-check"></i>Save &amp; finish</button>
                </div>
            </header>
            <div class="input-group-list">
                <div class="input-group">
                    <label>Template name</label>
                    <input name="template-name" type="text" placeholder="Enter template name" value="{{ project.entry_template.name }}" required>
                </div>
                <input id="clone-from" name="clone-from" type="hidden" value="">
                <div class="info" hidden>
                    <div class="buttons">
                        <input type="submit" name="share" value="Share" id="share">
                        <input type="submit" name="clone" value="Clone &amp; save changes" id="clone">
                    </div>
                </div>
            </div>
        </form>
        {% if project.entry_template.snapshot_pageone %}
        <div class="snapshots-container">
            <label>Template preview</label>
            <button id="snapshot-next"><i class="fa fa-chevron-right"></i></button>
            <a href="{% url 'custom_admin:entry_template' project.entry_template.pk %}?redirect={{ request.path|urlencode }}" id="edit-framework"><i class="fa fa-pencil"></i><span>Edit Framework</span></a>
            <button id="snapshot-prev" hidden><i class="fa fa-chevron-left"></i></button>
            <div class="snapshots">
                <img class="snapshot-page-one active" src="{{ project.entry_template.snapshot_pageone }}">
                <img class="snapshot-page-two" src="{{ project.entry_template.snapshot_pagetwo }}" hidden>
            </div>
        </div>
        {% else %}
        <a class = "no-snapshot-link" href="{% url 'custom_admin:entry_template' project.entry_template.pk %}?redirect={{ request.path|urlencode }}" id="edit-framework-no-snapshot"><i class="fa fa-pencil"></i><span>Edit Framework</span></a>
        {% endif %}
    </div>
    <div class="modal-container" hidden>
        <div class="modal" id="clone-viewer" hidden>
            <header>
                <h3 class="modal-header">Analysis framework</h3>
            </header>
            <div class="error"></div>
            <div class="snapshots-container">
                <button id="modal-snapshot-next"><i class="fa fa-chevron-right"></i></button>
                <button id="modal-snapshot-prev" hidden><i class="fa fa-chevron-left"></i></button>
                <div class="snapshots">
                    <img class="snapshot-page-one active">
                    <img class="snapshot-page-two" hidden>
                </div>
            </div>
            <div class="action-buttons">
                <button class="cancel-button" data-action="dismiss"><i class="fa fa-times fa-md"></i>Cancel</button>
                <div>
                    <button class="share-button" data-action="share" data-persist="true">Share</button>
                    <button class="clone-button" data-action="clone" data-persist="true">Clone</button>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

project/templates/project/geo-area.html
{% extends 'base.html' %}
{% load watchful_url %}

{% block title %}
DEEP | Geo Area
{% endblock %}

{% block head %}

<link rel="stylesheet" type="text/css" href="{% watchful_static_url 'css/selectize.css' %}" />
<link rel="stylesheet" type="text/css" href="{% watchful_static_url 'css/geo-area.css' %}" />
<script type="text/javascript" src="{% watchful_static_url 'js/common/selectize.js' %}"></script>
<script type="text/javascript" src="{% watchful_static_url 'js/common/utils.js' %}"></script>
<script type="text/javascript" src="{% watchful_static_url 'js/custom-admin/country-management/map.js' %}"></script>
<script type="text/javascript" src="{% watchful_static_url 'js/custom-admin/country-management/general-tab.js' %}"></script>
<script type="text/javascript" src="{% watchful_static_url 'js/project/geo-area.js' %}"></script>

<link rel="stylesheet" href="https://unpkg.com/leaflet@0.7.7/dist/leaflet.css"/>
<script src="https://unpkg.com/leaflet@0.7.7/dist/leaflet.js"></script>

<link rel="stylesheet" href="{% watchful_static_url 'css/leaflet.label.css' %}" >
<script src="{% watchful_static_url 'js/common/leaflet.label.js' %}"></script>

<script>
let countries = {
    {% for country in project.countries.all %}
    '{{ country.code }}': {
        modified: {% if country.reference_country %}true{% else %}false{% endif %},
        code: {% if country.reference_country %}'{{ country.reference_country.code }}'{% else %}'{{ country.code }}'{% endif %},
        name: '{{ country.name|escapejs }}',
        region: JSON.parse('{{ country.regions|escapejs }}'),
        admin_levels: [
            {% for admin_level in country.adminlevel_set.all %}
            {
                id: '{{ admin_level.pk }}', level: '{{ admin_level.level }}',
                name: '{{ admin_level.name|escapejs }}', property_name: '{{ admin_level.property_name|escapejs }}',
                property_pcode: ' {{ admin_level.property_pcode|escapejs }}',
                geojson: '{% if admin_level.geojson %}{{admin_level.geojson.url}}{% endif %}',
            },
            {% endfor %}
        ]
    },
    {% endfor %}
};
</script>

{% endblock %}

{% block body %}
{% include 'simplified-navbar.html' with page_title="Project Management Panel" %}

<aside>
    <header>
        <h2>Related admin boundaries</h2>
        <div class="search-block">
            <i class="fa fa-search"></i>
            <input id="search-geoarea" type="search" name="project-search" placeholder="Search Geo Areas">
        </div>
    </header>
    <div id="admin-boundary-list">
        {% for country in project.countries.all %}
        <div class="admin-boundary" data-country-code="{{ country.code }}" data-name="{{ country.name }}">{{ country.name }}</div>
        {% endfor %}
    </div>
</aside>
<main>
    <header>
        <a onclick="return confirmChanges()" href="{% url 'project:project_details' project_id %}">1. Project details</a>
        <a class="active">2. Geo area</a>
        <a onclick="return confirmChanges()" href="{% url 'project:analysis_framework' project_id %}" >3. Analysis framework</a>
    </header>
    <div id="admin-boundary-detail">
        {% if not project.countries.all %}
            <div class="no-countries">
                <p>No countries selected</p>
                <p>Please select a country in Project Details tab</p>
            </div>
        {% else %}
        <form method="post">
            {% csrf_token %}
            <header>
                <h3>Edit admin boundary <small></small></h3>
                <div class="action-buttons">
                    <button id="save-btn" name="save"> <i class='fa fa-save'></i>Save geo area</button>
                    <button id="save-and-proceed-btn" name="save-and-proceed"> <i class='fa fa-arrow-right'></i>Save &amp; proceed</button>
                </div>
            </header>
            <div class="input-group-list">
                <div>
                    <div id="country-detail-inputs">
                        <input id="selected-country-code" name="actual-code" type="hidden">
                        <input id="selected-country-modified" name="modified" type="hidden" value="0">

                        <div class="input-groups">
                            <div class="input-group" id="country-code-input">
                                <label>Code</label>
                                <input name="country-code" type="text" id="country-code" required>
                            </div>
                            <div class="input-group" id="country-name-input">
                                <label>Name</label>
                                <input name="country-name" type="text" id="country-name" placeholder="Enter country name" required>
                            </div>
                        </div>
                        <div class="input-group">
                            <label>WB region</label>
                            <input name="country-wb-region" type="text" id="country-wb-region" placeholder="Enter WB Region">
                        </div>
                        <div class="input-group">
                            <label>WB income group</label>
                            <input name="country-wb-income-group" type="text" id="country-wb-income-group" placeholder="Enter WB Income Group">
                        </div>
                        <div class="input-group">
                            <label>OCHA Region</label>
                            <input name="country-ocha-region" type="text" id="country-ocha-region" placeholder="Enter OCHA Region">
                        </div>
                        <div class="input-group">
                            <label>ECHO Region</label>
                            <input name="country-echo-region" type="text" id="country-echo-region" placeholder="Enter ECHO Region">
                        </div>
                        <div class="input-group">
                            <label>UN Geographical region</label>
                            <input name="country-un-geographical-region" type="text" id="country-un-geographical-region" placeholder="Enter UN Geographical Region">
                        </div>
                        <div class="input-group">
                            <label>UN Geographical Sub Region</label>
                            <input name="country-un-geographical-sub-region" type="text" id="country-un-geographical-sub-region" placeholder="Enter UN Geographical Sub Region">
                        </div>
                    </div>
                    <div id="map-container">
                        <div id="the-map">
                        </div>
                        <div id="map-controls">
                            <div id="admin-level-buttons"></div>
                        </div>
                    </div>
                </div>
                <div id="admin-level-list">
                    <header>
                        <h4>Admin Levels</h4>
                        <a id="add-new-admin-level"><i class="fa fa-plus"></i>Add new</a>
                    </header>
                    <div id="admin-levels">

                    </div>
                </div>
            </div>
        </form>
        {% endif %}

    </div>
</main>

<div class="admin-level-details-template" hidden>
    <input name="admin-level-pk" class="admin-level-pk" value="new" type="hidden">
    <div class="input-group" id="admin-level-input">
        <label>Level</label>
        <input name="admin-level" type="number" min="0" step="1" class="admin-level" placeholder="Enter admin level">
    </div>
    <div class="input-group">
        <label>Level Name</label>
        <input name="admin-level-name" type="text" class="admin-level-name" placeholder="Enter admin level name">
    </div>
    <div class="input-group">
        <label>Property name</label>
        <input name="property-name" type="text" class="property-name" placeholder="Enter property name">
    </div>
    <div class="input-group">
        <label>Property pcode</label>
        <input name="property-pcode" type="text" class="property-pcode" placeholder="Enter property pcode">
    </div>
    <div class="input-group-file">
        <label>GeoJSON file:</label>
        <input id="geojson-file-input" name="geojson" type="file" class="geojson file-input">
        <label for="geojson-file-input" class="geojson-label"><i class="fa fa-upload"></i>Choose a file</label>
        <p class="geojson-current"></p>
        <p class="geojson-old"></p> <input type="hidden" name="geojson-selected" class="geojson-selected" value="false">
    </div>
    {% comment %}
        Note that by putting a hidden input followed by checkbox input, we will get only the hidden value (0)
        if checkbox was not checked and both the checkbox and hidden values (1, 0) if it was.
    {% endcomment %}
    <div class="input-group-checkbox">
        <label><input name="delete-admin-level" type="checkbox" class="delete-admin-level" value="1"><span>Delete</span></label>
        <input name="delete-admin-level" type="hidden" value="0">
    </div>
</div>
{% endblock %}