custom_admin/urls.py
from django.conf.urls import url, include
from custom_admin import views


urlpatterns = [
    url(r'^project-panel/$', views.ProjectPanelView.as_view(), name="project_panel"),
    url(r'^country-management/$', views.CountryManagementView.as_view(), name="country_management"),
    url(r'^entry-template/(?P<template_id>\d+)/$', views.EntryTemplateView.as_view(), name="entry_template"),
]

deep/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from django.core.urlresolvers import reverse_lazy

from rest_framework.routers import DefaultRouter

from users.views import *
from deep.views import *
from report.views import *
from entries.views import ExportProgressView, WebsiteInfoView

from users.rest_views import *
from usergroup.rest_views import *
from leads.rest_views import *
from entries.rest_views import *
from deep.api_views import OverviewApiView, ReportsApiView


router = DefaultRouter()
router.register(r'leads', LeadViewSet, base_name='lead')
router.register(r'entries', EntryViewSet, base_name='entry')
router.register(r'entry-templates', EntryTemplateViewSet, base_name='entry-template')
router.register(r'sources', SourceViewSet, base_name='source')
router.register(r'events', EventViewSet, base_name='event')
router.register(r'events2', EventViewSet2, base_name='event2')
router.register(r'users', UserViewSet, base_name='user')
router.register(r'user-groups', UserGroupViewSet, base_name='user-group')
router.register(r'users2', UserViewSet2, base_name='user')
router.register(r'countries', CountryViewSet, base_name='country')
router.register(r'survey-of-surveys', SosViewSet, base_name='country')


urlpatterns = [

    ## ERROR PAGES
    url(r'^404/$', TemplateView.as_view(template_name='404.html')),
    url(r'^500/$', TemplateView.as_view(template_name='500.html')),

    url(r'^$', IndexView.as_view()),
    url(r'^register/$', RegisterView.as_view(), name="register"),
    url(r'^hid-access-token$', HidAccessToken.as_view(), name="hid_access_token"),
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    url(r'^extension/$', ExtensionView.as_view(), name="extension"),

    url(r'^load/countries/$', LoadCountries.as_view()),

    url(r'^dashboard/$', DashboardView.as_view(), name="dashboard"),
    url(r'^export-progress/$', ExportProgressView.as_view(), name="export_progress"),
    url(r'^download-file/$', DownloadFileView.as_view(), name="download_file"),

    url(r'^(?P<event>\d+)/dashboard/$', DashboardView.as_view(), name="dashboard"),
    url(r'^(?P<event>\d+)/leads/', include('leads.urls', namespace='leads')),
    url(r'^(?P<event>\d+)/entries/', include('entries.urls', namespace='entries')),

    url(r'^project/(?P<project_id>\d+)/', include('project.urls', namespace='project')),
    url(r'^usergroup/', include('usergroup.urls', namespace='usergroup')),
    url(r'^custom-admin/', include('custom_admin.urls', namespace='custom_admin')),
    url(r'^report/', include('report.urls', namespace='report')),

    url(r'^user/(?P<user_id>\d+)', UserProfileView.as_view(), name="user_profile"),

    # API for chrome extension
    url(r'user/status/', UserStatusView.as_view(), name="status"),
    url(r'date/', DateExtractorView.as_view(), name="date"),

    url(r'^admin/', admin.site.urls),
    url(r'^api/v1/', include(router.urls)),
    url(r'^api/v2/', include('entries.api_urls', namespace='api_entries')),
    url(r'^api/v2/', include('leads.api_urls', namespace='api_leads')),
    url(r'^api/v2/', include('report.api_urls', namespace='api_report')),

    url(r'api/v2/website-info/',
        WebsiteInfoView.as_view(), name='website_info'),

    url(r'^api/v2/dashboard/overview/$', OverviewApiView.as_view()),
    url(r'^api/v2/dashboard/reports/$', ReportsApiView.as_view()),

    url(r'^password/reset/$',
        auth_views.password_reset,
        {'post_reset_redirect': reverse_lazy('password_rest_done')},
        name="password_reset"),

    url(r'^password/reset/done/$',
        auth_views.password_reset_done,
        name="password_rest_done"),

    url(r'^password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        auth_views.password_reset_confirm,
        {'post_reset_redirect': reverse_lazy('password_reset_complete')},
        name="password_reset_confirm"),

    url(r'^password/done/$',
        auth_views.password_reset_complete,
        name="password_reset_complete"),

    url(r'^password/change/$',
        auth_views.password_change,
        name="password_change"),

    url(r'^password/change/done/$',
        auth_views.password_change,
        name="password_change_done"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

entries/urls.py
from django.conf.urls import url  # , include
from entries import views


urlpatterns = [
    url(r'^$', views.EntriesView.as_view(), name="entries"),

    url(r'^add/(?P<lead_id>\d+)/$', views.AddEntry.as_view(), name='add'),
    url(r'^edit/(?P<id>\d+)/$', views.AddEntry.as_view(), name='edit'),

    url(r'^add/(?P<lead_id>\d+)/$',
        views.AddEntry.as_view(), name='add'),
    url(r'^edit/(?P<id>\d+)/$',
        views.AddEntry.as_view(), name='edit'),

    url(r'^export/$', views.ExportView.as_view(), name="export"),
    url(r'^exportxls/$', views.ExportXls.as_view(), name="exportxls"),
    url(r'^exportxls/weekly$', views.ExportXlsWeekly.as_view(),
        name="exportxls_weekly"),
    url(r'^exportdoc/$', views.ExportDoc.as_view(), name="exportdoc"),

    url(r'^delete/$', views.DeleteEntry.as_view(), name='delete'),
]

leads/urls.py
from django.conf.urls import url, include
from leads import views


urlpatterns = [
    url(r'^$', views.LeadsView.as_view(), name="leads"),
    url(r'^add/$', views.AddLead.as_view(), name='add'),
    url(r'^add-sos/(?P<lead_id>\d+)/$', views.AddSoS.as_view(), name='add_sos'),
    url(r'^edit-sos/(?P<lead_id>\d+)/(?P<sos_id>\d+)/$', views.AddSoS.as_view(), name='edit_sos'),
    url(r'^edit/(?P<id>\d+)/$', views.AddLead.as_view(), name='edit'),
    url(r'^mark_processed/$', views.MarkProcessed.as_view(), name='mark_processed'),
    url(r'^delete/$', views.DeleteLead.as_view(), name='delete'),
    url(r'^delete-sos/$', views.DeleteSoS.as_view(), name='delete_sos'),
    url(r'^sos/$', views.SoSView.as_view(), name="sos"),

    url(r'^exportsosxls/$', views.ExportSosXls.as_view(), name="exportsosxls"),
]

project/urls.py
from django.conf.urls import url, include
from project.views import *


urlpatterns = [
    url(r'^details/$', ProjectDetailsView.as_view(), name="project_details"),
    url(r'^geo-area/$', GeoAreaView.as_view(), name="geo_area"),
    url(r'^analysis-framework/$', AnalysisFrameworkView.as_view(), name="analysis_framework"),
]

templates/base.html
{% load watchful_url %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">

    <meta name="description" content="">
    <meta name="author" content="">

    <link rel='shortcut icon' href="{% watchful_static_url 'img/favicon.png' %}" type='image/x-icon' >

    <title>{% block title %}DEEP{% endblock %}</title>

    <script src="{% watchful_static_url 'js/common/jquery.min.js' %}"></script>

    {% block head %}
    {% endblock %}

    <link rel="stylesheet" type="text/css" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css"/>
    <script type="text/javascript" src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
</head>
<body>
    <div class="float-alert-toast">
    </div>
    {% block body %}
    {% endblock %}

    <div class="issue-collector">
        <button id="finance-a-feature">Finance a feature <span class="fa fa-money"></span></button>
        <button id="report-a-bug">Feedback? Found a Bug?</span></button>
    </div>

    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Inconsolata" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

    <script type="text/javascript" src="https://togglecorp.atlassian.net/s/d41d8cd98f00b204e9800998ecf8427e-T/g6wb3c/b/c/7ebd7d8b8f8cafb14c7b0966803e5701/_/download/batch/com.atlassian.jira.collector.plugin.jira-issue-collector-plugin:issuecollector/com.atlassian.jira.collector.plugin.jira-issue-collector-plugin:issuecollector.js?locale=en-US&collectorId=aaa59b20"></script>
    <script type="text/javascript" src="https://togglecorp.atlassian.net/s/d41d8cd98f00b204e9800998ecf8427e-T/c8vwe6/b/a/7ebd7d8b8f8cafb14c7b0966803e5701/_/download/batch/com.atlassian.jira.collector.plugin.jira-issue-collector-plugin:issuecollector/com.atlassian.jira.collector.plugin.jira-issue-collector-plugin:issuecollector.js?locale=en-US&collectorId=13c893d9"></script>
    <script>
        window.ATL_JQ_PAGE_PROPS = $.extend(window.ATL_JQ_PAGE_PROPS,{
            'aaa59b20': {
                triggerFunction: function(showCollectorDialog) {
                    $("#report-a-bug").click(function(e) {
                        e.preventDefault();
                        showCollectorDialog();
                    });
                }
            },
            '13c893d9': {
                triggerFunction: function(showCollectorDialog) {
                    $("#finance-a-feature").click(function(e) {
                        e.preventDefault();
                        showCollectorDialog();
                    });
                }
            },
        });
    </script>
    <script>
    // script for Google Analytics
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-88197525-1', 'auto');
    ga('send', 'pageview'{% if user %}, {user_id: '{{user.pk}}'} {% endif %});
    </script> 
</body>
</html>

templates/navbar.html
{% load watchful_url %}
{% load check_acaps %}

<script>
    $(document).ready(function(){
        {% if all_events %}
        var currentDropdownVal = $('#project-dropdown').val();

        var projectDropdown = $('#project-dropdown').selectize({
            onDropdownOpen: function(dropdown) {
                projectDropdown.clear();
                //dropdown.stop().hide().slideToggle();
            },
            onDropdownClose: function(dropdown) {
                if(projectDropdown.getValue() == ''){
                    projectDropdown.setValue(currentDropdownVal);
                }
                //dropdown.stop().show().slideToggle();
            }
        })[0].selectize;
        $('#project-dropdown').change(function() {
            if ($(this).val() != null && $(this).val() != '' && $(this).val() != currentDropdownVal){
                window.location.href = $(this).val();
            }
        });
        {% endif %}

        $('body nav').on('click', '.dropdown-toggle', function(){
            $(this).closest('.dropdown').find('.items').toggle();
        });
        $(document).on('click', function(e) {
            if (!$('body nav .dropdown').is(e.target) && $('body nav .dropdown').has(e.target).length == 0) {
                $('body nav .dropdown').find('.items').hide();
            }
        });

        $('div[data-url]').click(function() {
            if ($(this).data('target') == 'new-tab') {
                window.open($(this).data('url'), '_blank');
            } else {
                window.location.href = $(this).data('url');
            }
        });
    });
</script>

<nav>
    <!-- DEEP logo -->
    <div id="deep-logo-container">
        {% if event %}
        <a href="{% url 'dashboard' event=event.pk%}"><img src="{% watchful_static_url 'img/deep-logo-white.png' %}"></a>
        {% else %}
        <a href="{% url 'dashboard' %}?last_event=1"><img src="{% watchful_static_url 'img/deep-logo-white.png' %}"></a>
        {% endif %}
    </div>

    <!-- Report -->


    <!-- Event selector -->
    <div id="project-select-container">
        {% if all_events %}
        <select id="project-dropdown" placeholder="Select event">
            <option>Select event</option>
            {% if request.user|allow_acaps %}
            {% if event %}
            <option value="{% url 'dashboard' %}">All events</option>
            {% else %}
            <option value="{% url request.resolver_match.view_name 0 %}" selected>All events</option>
            {% endif %}
            {% endif %}
            {% for ev in all_events %}
            <option value="{% url request.resolver_match.view_name event=ev.pk %}" {% if event and event == ev %}selected{% endif %}>{{ev}}</option>
            {% endfor %}
        </select>
        {% else %}
        {% if event %}
        <div id="project-dropdown-alt"><span class="fa fa-location-arrow"></span>{{event}}</div>
        {% endif %}
        {% endif %}
    </div>

    <!-- Main menu -->
    <div id="main-menu">
        {% if event %}
            <a class="{% if current_page == 'leads' %}active{% endif %} menu-item" href="{% url 'leads:leads' event=event.pk %}">Leads</a>
            <a class="{% if current_page == 'entries' %}active{% endif %} menu-item" href="{% url 'entries:entries' event=event.pk %}">Entries</a>

            {% if event.is_acaps %}
            <a class="{% if current_page == 'sos' %}active{% endif %} menu-item" href="{% url 'leads:sos' event=event.pk %}">Assessment Registry</a>
            <a class="{% if current_page == 'report' %}active{% endif %} menu-item" href="{% url 'report:dashboard' %}?event={{event.pk}}&country={{event.countries.all.0.code}}">Weekly Snapshot</a>
            {% endif %}

            <a class="{% if current_page == 'export' %}active{% endif %} menu-item" href="{% url 'entries:export' event=event.pk %}">Export</a>
        {% else %}
            <a class="{% if current_page == 'leads' %}active{% endif %} menu-item" href="{% url 'leads:leads' 0 %}">Leads</a>
            <a class="{% if current_page == 'entries' %}active{% endif %} menu-item" href="{% url 'entries:entries' 0 %}">Entries</a>
        {% endif %}
    </div>
    <div id="extra-menu">
        <!-- Chrome extension download -->
        <a id="chrome-extension-download-link" target="_blank" title="Download Chrome Extension" href="https://chrome.google.com/webstore/detail/deep-create-lead/ggplhkhciodfdkkonmhgniaopboeoopi"><i class="fa fa-chrome fa-spin"></i></a>

        <!-- User menu -->
        <div class="dropdown" id="user-menu" tabindex="-1">
            <a class="dropdown-toggle"><div class="name"><i class="fa fa-user"></i>{{ user.first_name }}</div><i class="fa fa-chevron-down"></i></a>
            <div class="items" hidden>
                <a href="{% url 'user_profile' user.pk %}"><i class="fa fa-user"></i>Profile</small></a>
                {% if request.user.is_superuser %}
                <a href="/admin"><i class="fa fa-user-secret"></i>Admin panel</a>
                <a href="{% url 'custom_admin:country_management' %}"><i class="fa fa-globe"></i>Country Panel</a>
                {% endif %}

                {% if event and request.user in event.get_admins %}
                <a href="{% url 'project:project_details' event.pk %}"><i class="fa fa-wrench"></i>Project Panel</a>
                {% endif %}

                <hr>
                {% comment %}
                <a href="{% url 'password_change' %}"><i class="fa fa-key"></i>Change password</small></a>
                {% if not request.user.userprofile.hid %}
                <a id="link-with-hid"><i class="fa fa-link"></i>Link with HID</a>
                {% endif %}
                {% endcomment %}
                <a onclick="window.location.href = '{% url 'logout' %}';"><i class="fa fa-sign-out"></i>Logout</a>
            </div>
        </div>
    </div>
</nav>

templates/navigation-bar.html
{% load staticfiles %}

<div class="section" id="header-section">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2 col-sm-6">
                {% if event %}
                <a class="app-name" href="{% url 'dashboard' event=event.pk%}">
                    <img class="logo" src="{% static 'img/deep-logo-white.png' %}">
                </a>
                {% else %}
                <a class="app-name" href="{% url 'dashboard' %}">
                    <img class="logo" src="{% static 'img/deep-logo-white.png' %}">
                </a>
                {% endif %}
            </div>
            <div class="col-md-2 col-sm-6">
                <div class="dropdown" id="event-menu">
                    {% if all_events %}
                    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                        <i class="fa fa-location-arrow"></i>{% if event %} {{event}} {% else %} Select an event {% endif %}<span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                        {% for ev in all_events %}
                        <li><a href="{% url request.resolver_match.view_name event=ev.pk %}">{{ev}}</a></li>
                        {% endfor %}
                        <li><a href="{% url 'dashboard' %}">None</a></li>
                    </ul>
                    {% else %}
                    <button class="btn btn-primary dropdown-toggle" type="button" enabled="disabled" data-toggle="dropdown">
                        {% if event %} <i class="fa fa-location-arrow"></i>{{event}}{% endif %}
                    </button>
                    {% endif %}
                </div>
            </div>
            <div class="col-md-6 col-sm-8">
                <div class="menu">
                    {% if event and all_events %}
                    <a class="{% if current_page == 'leads' %}active{% endif %} menu-item" href="{% url 'leads:leads' event=event.pk %}">Leads</a>
                    <a class="{% if current_page == 'entries' %}active{% endif %} menu-item" href="{% url 'entries:entries' event=event.pk %}">Entries</a>
                    <a class="{% if current_page == 'export' %}active{% endif %} menu-item" href="{% url 'entries:export' event=event.pk %}">Export</a>
                    {% endif %}
                </div>
            </div>
            <div class="col-md-2 col-sm-4">
                <div class="dropdown" id="user-menu">
                    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                        <i class="fa fa-user"></i>{{ user.first_name }}<span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                        {% if request.user.is_superuser %}
                        <li><a href="/admin"><i class="fa fa-user-secret"></i>Admin panel</a></li>
                        {% endif %}
                        <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out"></i>Logout</a></li>
                    </ul>
                </div>

            </div>
        </div>
    </div>
</div>

templates/simplified-navbar.html
{% load watchful_url %}
<script>
    $(document).ready(function(){
        $('body nav').on('click', '.dropdown-toggle', function(){
            $(this).closest('.dropdown').find('.items').toggle();
        });
    });
    $(document).on('click', function(e) {
        if (!$('body nav .dropdown').is(e.target) && $('body nav .dropdown').has(e.target).length == 0) {
            $('body nav .dropdown').find('.items').hide();
        }
    });
    $('div[data-url]').click(function() {
        if ($(this).data('target') == 'new-tab') {
            window.open($(this).data('url'), '_blank');
        } else {
            window.location.href = $(this).data('url');
        }
    });
</script>
<nav>
    <div id="left-part">
        <!-- DEEP logo -->
        <div id="deep-logo-container">
            {% if event %}
            <a href="{% url 'dashboard' event=event.pk%}"><img src="{% watchful_static_url 'img/deep-logo-sm-white.png' %}"></a>
            {% else %}
            <a href="{% url 'dashboard' %}?last_event=1"><img src="{% watchful_static_url 'img/deep-logo-sm-white.png' %}"></a>
            {% endif %}
        </div>
        <h2>{{ page_title }}</h2>
    </div>
    <!-- User menu -->
    <div class="dropdown" id="user-menu" tabindex="-1">
        <a class="dropdown-toggle"><div class="name"><i class="fa fa-user"></i>{{ user.first_name }}</div><i class="fa fa-chevron-down"></i></a>
        <div class="items" hidden>
            <a href="{% url 'user_profile' user.pk %}"><i class="fa fa-user"></i>Profile</small></a>

            {% if request.user.is_superuser %}
            <a href="/admin"><i class="fa fa-user-secret"></i>Admin panel</a>
            <a href="{% url 'custom_admin:country_management' %}"><i class="fa fa-globe"></i>Country Panel</a>
            {% endif %}

            {% if event and request.user in event.get_admins %}
            <a href="{% url 'project:project_details' event.pk %}"><i class="fa fa-wrench"></i>Project Panel</a>
            {% endif %}

            <hr>
            <a href="{% url 'password_change' %}"><i class="fa fa-key"></i>Change password</small></a>
            {% if not request.user.userprofile.hid %}
            <a id="link-with-hid"><i class="fa fa-link"></i>Link with HID</a>
            {% endif %}
            <a onclick="window.location.href = '{% url 'logout' %}';"><i class="fa fa-sign-out"></i>Logout</a>
        </div>
    </div>
</nav>