deep/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from django.core.urlresolvers import reverse_lazy

from rest_framework.routers import DefaultRouter

from users.views import *
from deep.views import *
from report.views import *
from entries.views import ExportProgressView, WebsiteInfoView

from users.rest_views import *
from usergroup.rest_views import *
from leads.rest_views import *
from entries.rest_views import *
from deep.api_views import OverviewApiView, ReportsApiView


router = DefaultRouter()
router.register(r'leads', LeadViewSet, base_name='lead')
router.register(r'entries', EntryViewSet, base_name='entry')
router.register(r'entry-templates', EntryTemplateViewSet, base_name='entry-template')
router.register(r'sources', SourceViewSet, base_name='source')
router.register(r'events', EventViewSet, base_name='event')
router.register(r'events2', EventViewSet2, base_name='event2')
router.register(r'users', UserViewSet, base_name='user')
router.register(r'user-groups', UserGroupViewSet, base_name='user-group')
router.register(r'users2', UserViewSet2, base_name='user')
router.register(r'countries', CountryViewSet, base_name='country')
router.register(r'survey-of-surveys', SosViewSet, base_name='country')


urlpatterns = [

    ## ERROR PAGES
    url(r'^404/$', TemplateView.as_view(template_name='404.html')),
    url(r'^500/$', TemplateView.as_view(template_name='500.html')),

    url(r'^$', IndexView.as_view()),
    url(r'^register/$', RegisterView.as_view(), name="register"),
    url(r'^hid-access-token$', HidAccessToken.as_view(), name="hid_access_token"),
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    url(r'^extension/$', ExtensionView.as_view(), name="extension"),

    url(r'^load/countries/$', LoadCountries.as_view()),

    url(r'^dashboard/$', DashboardView.as_view(), name="dashboard"),
    url(r'^export-progress/$', ExportProgressView.as_view(), name="export_progress"),
    url(r'^download-file/$', DownloadFileView.as_view(), name="download_file"),

    url(r'^(?P<event>\d+)/dashboard/$', DashboardView.as_view(), name="dashboard"),
    url(r'^(?P<event>\d+)/leads/', include('leads.urls', namespace='leads')),
    url(r'^(?P<event>\d+)/entries/', include('entries.urls', namespace='entries')),

    url(r'^project/(?P<project_id>\d+)/', include('project.urls', namespace='project')),
    url(r'^usergroup/', include('usergroup.urls', namespace='usergroup')),
    url(r'^custom-admin/', include('custom_admin.urls', namespace='custom_admin')),
    url(r'^report/', include('report.urls', namespace='report')),

    url(r'^user/(?P<user_id>\d+)', UserProfileView.as_view(), name="user_profile"),

    # API for chrome extension
    url(r'user/status/', UserStatusView.as_view(), name="status"),
    url(r'date/', DateExtractorView.as_view(), name="date"),

    url(r'^admin/', admin.site.urls),
    url(r'^api/v1/', include(router.urls)),
    url(r'^api/v2/', include('entries.api_urls', namespace='api_entries')),
    url(r'^api/v2/', include('leads.api_urls', namespace='api_leads')),
    url(r'^api/v2/', include('report.api_urls', namespace='api_report')),

    url(r'api/v2/website-info/',
        WebsiteInfoView.as_view(), name='website_info'),

    url(r'^api/v2/dashboard/overview/$', OverviewApiView.as_view()),
    url(r'^api/v2/dashboard/reports/$', ReportsApiView.as_view()),

    url(r'^password/reset/$',
        auth_views.password_reset,
        {'post_reset_redirect': reverse_lazy('password_rest_done')},
        name="password_reset"),

    url(r'^password/reset/done/$',
        auth_views.password_reset_done,
        name="password_rest_done"),

    url(r'^password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        auth_views.password_reset_confirm,
        {'post_reset_redirect': reverse_lazy('password_reset_complete')},
        name="password_reset_confirm"),

    url(r'^password/done/$',
        auth_views.password_reset_complete,
        name="password_reset_complete"),

    url(r'^password/change/$',
        auth_views.password_change,
        name="password_change"),

    url(r'^password/change/done/$',
        auth_views.password_change,
        name="password_change_done"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

entries/urls.py
from django.conf.urls import url  # , include
from entries import views


urlpatterns = [
    url(r'^$', views.EntriesView.as_view(), name="entries"),

    url(r'^add/(?P<lead_id>\d+)/$', views.AddEntry.as_view(), name='add'),
    url(r'^edit/(?P<id>\d+)/$', views.AddEntry.as_view(), name='edit'),

    url(r'^add/(?P<lead_id>\d+)/$',
        views.AddEntry.as_view(), name='add'),
    url(r'^edit/(?P<id>\d+)/$',
        views.AddEntry.as_view(), name='edit'),

    url(r'^export/$', views.ExportView.as_view(), name="export"),
    url(r'^exportxls/$', views.ExportXls.as_view(), name="exportxls"),
    url(r'^exportxls/weekly$', views.ExportXlsWeekly.as_view(),
        name="exportxls_weekly"),
    url(r'^exportdoc/$', views.ExportDoc.as_view(), name="exportdoc"),

    url(r'^delete/$', views.DeleteEntry.as_view(), name='delete'),
]

leads/urls.py
from django.conf.urls import url, include
from leads import views


urlpatterns = [
    url(r'^$', views.LeadsView.as_view(), name="leads"),
    url(r'^add/$', views.AddLead.as_view(), name='add'),
    url(r'^add-sos/(?P<lead_id>\d+)/$', views.AddSoS.as_view(), name='add_sos'),
    url(r'^edit-sos/(?P<lead_id>\d+)/(?P<sos_id>\d+)/$', views.AddSoS.as_view(), name='edit_sos'),
    url(r'^edit/(?P<id>\d+)/$', views.AddLead.as_view(), name='edit'),
    url(r'^mark_processed/$', views.MarkProcessed.as_view(), name='mark_processed'),
    url(r'^delete/$', views.DeleteLead.as_view(), name='delete'),
    url(r'^delete-sos/$', views.DeleteSoS.as_view(), name='delete_sos'),
    url(r'^sos/$', views.SoSView.as_view(), name="sos"),

    url(r'^exportsosxls/$', views.ExportSosXls.as_view(), name="exportsosxls"),
]

entries/models.py
from django.db import models
from django.contrib.auth.models import User
# from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver
from django.utils import timezone

from leads.models import *
from entries.load_geo_areas import load_geo_areas

import json


class AdminLevel(models.Model):
    level = models.IntegerField()
    country = models.ForeignKey(Country)
    name = models.CharField(max_length=70)
    property_name = models.CharField(max_length=70)
    property_pcode = models.CharField(max_length=50, default="", blank=True)
    geojson = models.FileField(upload_to='adminlevels/', default=None, blank=True, null=True)
    geo_areas = models.TextField(default='[]')

    def __str__(self):
        return self.name + ", " + str(self.country)

    class Meta:
        ordering = ['country', 'level']
        unique_together = ('country', 'level')

    def save(self, *args, **kwargs):
        self.geo_areas = json.dumps(load_geo_areas(self))
        super(AdminLevel, self).save(*args, **kwargs)


# @receiver(pre_delete, sender=AdminLevel)
# def _admin_level_delete(sender, instance, **kwargs):
#     instance.geojson.delete(False)


class AdminLevelSelection(models.Model):
    admin_level = models.ForeignKey(AdminLevel)
    name = models.CharField(max_length=70)
    pcode = models.CharField(max_length=50, default="", blank=True)

    def __str__(self):
        if self.pcode == "":
            return self.name + ", " + str(self.admin_level)
        else:
            return self.name + " (" + self.pcode + ")" + ", " + str(self.admin_level)

    def get_keyword(self):
        # "{{self.admin_level.country.code}}:{{self.admin_level.level|add:'-1'}}:{{self.name}}"
        if self.pcode != '':
            return str(self.admin_level.country.code) + ":" + str(self.admin_level.level) + ":" + str(self.name) + ":" + str(self.pcode)
        return str(self.admin_level.country.code) + ":" + str(self.admin_level.level) + ":" + str(self.name)


class Reliability(models.Model):
    name = models.CharField(max_length=100)
    level = models.IntegerField()
    is_default = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Reliabilities'
        ordering = ['level']


class Severity(models.Model):
    name = models.CharField(max_length=100)
    level = models.IntegerField()
    is_default = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Severities'
        ordering = ['level']


class AffectedGroup(models.Model):
    name = models.CharField(max_length=150)
    parent = models.ForeignKey("entries.AffectedGroup", blank=True, default=None, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Affected Groups"


class VulnerableGroup(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Vulnerable Groups"


class SpecificNeedsGroup(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Specific Needs Groups"


class InformationPillar(models.Model):
    name = models.CharField(max_length=150)
    contains_sectors = models.BooleanField(default=False)

    tooltip = models.TextField(default='', blank=True)

    background_color = models.CharField(max_length=20, default="#fbe8db")
    active_background_color = models.CharField(max_length=20, default="#ea7120")

    PEOPLE_IN_NEED = "PIN"
    HUMANITARIAN_ACCESS = "HAC"
    HUMANITARIAN_PROFILE = "HPR"
    CASUALTIES = "CAS"
    KEY_EVENTS = "KEY"

    APPEAR_IN = (
        (PEOPLE_IN_NEED, "People in need"),
        (HUMANITARIAN_ACCESS, "Humanitarian access"),
        (HUMANITARIAN_PROFILE, "Humanitarian profile"),
        (CASUALTIES, "Casualties"),
        (KEY_EVENTS, "Key events"),
    )

    appear_in = models.CharField(max_length=3, choices=APPEAR_IN,
                                 blank=True, null=True, default=None)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Information Pillars"


class InformationSubpillar(models.Model):
    name = models.CharField(max_length=150)
    pillar = models.ForeignKey(InformationPillar)

    tooltip = models.TextField(default='', blank=True)

    PEOPLE_IN_NEED = "PIN"
    HUMANITARIAN_ACCESS = "HAC"
    HUMANITARIAN_PROFILE = "HPR"
    CASUALTIES = "CAS"
    KEY_EVENTS = "KEY"

    APPEAR_IN = (
        (PEOPLE_IN_NEED, "People in need"),
        (HUMANITARIAN_ACCESS, "Humanitarian access"),
        (HUMANITARIAN_PROFILE, "Humanitarian profile"),
        (CASUALTIES, "Casualties"),
        (KEY_EVENTS, "Key events"),
    )

    appear_in = models.CharField(max_length=3, choices=APPEAR_IN,
                                 blank=True, null=True, default=None)

    def __str__(self):
        return self.name


class Sector(models.Model):
    name = models.CharField(max_length=150)
    icon = models.FileField(upload_to="sector-icons/", null=True, blank=True, default=None)

    def __str__(self):
        return self.name


# @receiver(pre_delete, sender=Sector)
# def _sector_delete(sender, instance, **kwargs):
#     instance.icon.delete(False)


class Subsector(models.Model):
    sector = models.ForeignKey(Sector)
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name


class Entry(models.Model):
    modified_at = models.DateTimeField(auto_now=True)
    modified_by = models.ForeignKey(User, default=None, null=True, blank=True)
    created_at = models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey(User, default=None, null=True, blank=True, related_name='entries_created')
    lead = models.ForeignKey(Lead)

    # Following is for entries entered using template
    template = models.ForeignKey('entries.EntryTemplate', default=None,  null=True, blank=True)

    def __str__(self):
        return str(self.lead)

    class Meta:
        verbose_name_plural = 'Entries'


class EntryInformation(models.Model):
    entry = models.ForeignKey(Entry)
    excerpt = models.TextField(blank=True)
    image = models.TextField(blank=True, default='')

    # Following data is for old data type
    date = models.DateField(blank=True, default=None, null=True)
    reliability = models.ForeignKey(Reliability, default=None, null=True)
    severity = models.ForeignKey(Severity, default=None, null=True)
    number = models.IntegerField(blank=True, default=None, null=True)
    vulnerable_groups = models.ManyToManyField(VulnerableGroup, blank=True)
    specific_needs_groups = models.ManyToManyField(SpecificNeedsGroup, blank=True)
    affected_groups = models.ManyToManyField(AffectedGroup, blank=True)
    map_selections = models.ManyToManyField(AdminLevelSelection, blank=True)
    bob = models.BooleanField(default=False) # best of bullshits

    # Following is for entries entered using template
    elements = models.TextField(default='[]')

    def __str__(self):
        return self.excerpt


class InformationAttribute(models.Model):
    information = models.ForeignKey(EntryInformation)
    subpillar = models.ForeignKey(InformationSubpillar)
    sector = models.ForeignKey(Sector, blank=True, null=True, default=None)

    # TO DELETE
    subsector = models.ForeignKey(Subsector, blank=True, null=True, default=None, related_name='informationattribute_donot_use', verbose_name='DO NOT USE')

    subsectors = models.ManyToManyField(Subsector, blank=True)

    def __str__(self):
        return str(self.subpillar) + "/" + str(self.sector) + "/" + str(self.subsector)


class EntryTemplate(models.Model):
    name = models.CharField(max_length=150)
    elements = models.TextField(default='[]')
    snapshot_pageone = models.TextField(default=None, null=True)
    snapshot_pagetwo = models.TextField(default=None, null=True)
    created_by = models.ForeignKey(User)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def get_admins(self):
        return User.objects.filter(
            events_owned__entry_template=self
        ).distinct()


class ExportToken(models.Model):
    token = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    data = models.TextField(blank=True)

    def __str__(self):
        return self.name

entries/templates/entries/entry-filters.html
<div class="filter">
    <input type="text" id="search" class="filter" placeholder="Search excerpt">
</div>
<div class="filter">
    <select id="users-filter" multiple>
        <option value="">Imported by</option>
        {% for u in users %}
        <option value="{{u.pk}}">{{u.get_full_name}}</option>
        {% endfor %}
    </select>
</div>
<div class="filter" id="date-imported-filter-container">
    <select id="date-imported-filter">
        <option value="">Date last modified</option>
        <option value="today">Today</option>
        <option value="yesterday">Yesterday</option>
        <option value="last-seven-days">Last 7 days</option>
        <option value="this-week">This week</option>
        <option value="last-thirty-days">Last 30 days</option>
        <option value="this-month">This month</option>
        <option value="range">Range</option>
    </select>
</div>
<div class="filter">
    <input type="text" id="lead-title-search" class="filter" placeholder="Lead title">
</div>
<div class="filter">
    <input type="text" id="sources-filter" class="filter" placeholder="Source">
</div>
<div class="filter" id="date-published-filter-container">
    <select id="date-published-filter">
        <option value="">Date Published</option>
        <option value="today">Today</option>
        <option value="yesterday">Yesterday</option>
        <option value="last-seven-days">Last 7 days</option>
        <option value="this-week">This week</option>
        <option value="last-thirty-days">Last 30 days</option>
        <option value="this-month">This month</option>
        <option value="range">Range</option>
    </select>
</div>
<div class="filter range">
    <label>Reliability</label>
    <select id="reliabilities-min-filter" class="reliabilities-filter" placeholder="from">
        <option value="">from</option>
        {% for reliability in reliabilities %}
        <option value="{{reliability.level}}">{{reliability}}</option>
        {% endfor %}
    </select>
    <select id="reliabilities-max-filter" class="reliabilities-filter" placeholder="to">
        <option value="">to</option>
        {% for reliability in reliabilities %}
        <option value="{{reliability.level}}">{{reliability}}</option>
        {% endfor %}
    </select>
</div>
<div class="filter">
    <select id="areas-filter" multiple>
        <option value="">Geographical areas</option>
        {% for area in areas %}
        <option value="{{area}}">{{area}}</option>
        {% endfor %}
    </select>
</div>
<div class="filter">
    <select id="affected-groups-filter" multiple>
        <option value="">Affected groups</option>
        {% for group in affected_groups %}
        <option value="{{group}}">{{group}}</option>
        {% endfor %}
    </select>
</div>
<div class="filter">
    <select id="vulnerable-groups-filter" multiple>
        <option value="">Demographic group</option>
        {% for vulnerable_group in vulnerable_groups %}
        <option value="{{vulnerable_group}}">{{vulnerable_group}}</option>
        {% endfor %}
    </select>
</div>
<div class="filter">
    <select id="specific-needs-groups-filter" multiple>
        <option value="">Specific needs groups</option>
        {% for group in specific_needs_groups %}
        <option value="{{group}}">{{group}}</option>
        {% endfor %}
    </select>
</div>
<div class="filter">
    <select id="pillars-filter" multiple>
        <option value="">Pillars and subpillars</option>
        {% for pillar in pillars %}
        <option value="{{pillar.pk}}">{{pillar}}</option>
        {% for subpillar in pillar.informationsubpillar_set.all %}
        <option value="{{pillar.pk}}/{{subpillar.pk}}">{{pillar}} / {{subpillar}}</option>
        {% endfor %}
        {% endfor %}
    </select>
</div>
<div class="filter">
    <select id="sectors-filter" multiple>
        <option value="">Sectors and subsectors</option>
        {% for sector in sectors %}
        <option value="{{sector.pk}}">{{sector}}</option>
        {% for subsector in sector.subsector_set.all %}
        <option value="{{sector.pk}}/{{subsector.pk}}">{{sector}} / {{subsector}}</option>
        {% endfor %}
        {% endfor %}
    </select>
</div>
<div class="filter range">
    <label>Severity</label>
    <select id="severities-min-filter" class="severities-filter" placeholder="from">
        <option value="">from</option>
        {% for severity in severities %}
        <option value="{{severity.level}}">{{severity}}</option>
        {% endfor %}
    </select>
    <select id="severities-max-filter" class="severities-filter" placeholder="to">
        <option value="">to</option>
        {% for severity in severities %}
        <option value="{{severity.level}}">{{severity}}</option>
        {% endfor %}
    </select>
</div>

entries/templates/entries/export-leads.html
<div class="leads-container">
    <input id="selected-leads" type="hidden" name="leads">
    <header>
        <div class="select"><label><input type="checkbox">Select</label></div>
        <div class="created-at">Created on</div>
        <div class="title">Title</div>
    </header>
    <div class="leads">
        <div class="lead-template" hidden>
            <div class="select"><label><input type="checkbox"></label></div>
            <div class="created-at"></div>
            <div class="title"></div>
        </div>
    </div>
</div>

entries/templates/entries/export-progress.html
{% extends 'base.html' %}
{% load watchful_url %}

{% block title %}
DEEP | Export
{% endblock %}

{% block head %}
<link href="{% watchful_static_url 'css/export-progress.css' %}" type="text/css" rel="stylesheet">

<script>
    $(document).ready(function() {
        let url = "{% url 'download_file' %}?url=" + encodeURIComponent("{{ export_url }}");
        $.getJSON(url, function(data) {

            $('#loader').fadeOut(function() {
                $('#post-load').css('display', 'flex');
            });

            if(data.s3){
                window.location.href = data.url;
            }else{
                window.location.href = "{% url 'download_file' %}?path="
                    + encodeURIComponent(data.path) + "&filename="
                    + encodeURIComponent(data.filename) + "&content_type="
                    + encodeURIComponent(data.content_type);
            }
        });
    });
</script>
{% endblock %}

{% block body %}

<div id="loading-animation">
    <span id="loader"></span>
    <h2>Preparing data to download ...</h2>
    <p>This might take some time, please be patient</p>
</div>

<div id="post-load" hidden>
    <span class="fa fa-check fa-4x"></span>
    <h2>Data prepared succesfully</h2>
    <p>Your download should begin shortly</p>
</div>


{% endblock %}

entries/templates/entries/export.html
{% extends 'base.html' %}
{% load watchful_url %}

{% block title %}
DEEP | Export
{% endblock %}

{% block head %}
<link href="{% watchful_static_url 'css/jquery-ui.min.css' %}" type="text/css" rel="stylesheet">
<link href="{% watchful_static_url 'css/selectize.css' %}" type="text/css" rel="stylesheet"/>
<link href="{% watchful_static_url 'css/modal.css' %}" type="text/css" rel="stylesheet">
<link href="{% watchful_static_url 'css/export.css' %}" type="text/css" rel="stylesheet">

<script type="text/javascript" src="{% watchful_static_url 'js/common/selectize.js' %}"></script>
<script type="text/javascript" src="{% watchful_static_url 'js/common/modal.js' %}"></script>
<script type="text/javascript" src="{% watchful_static_url 'js/common/utils.js' %}"></script>
<script type="text/javascript" src="{% watchful_static_url 'js/common/jquery-ui.min.js' %}"></script>
<script type="text/javascript" src="{% watchful_static_url 'js/entries/export.js' %}"></script>

<script>
var eventId = "{{ event.pk }}";
var exportProgressUrl = "{% url 'export_progress' %}";
var downloadUrl = "{% url 'download_file' %}";

var pillars = [
    {% for pillar in pillars %}
    {
        id: "{{ pillar.pk }}",
        name: "{{ pillar.name|escapejs }}",
        contains_sectors: {% if pillar.contains_sectors %}true{% else %}false{% endif %},

        subpillars: [
            {% for subpillar in pillar.informationsubpillar_set.all %}
            { id: "{{ subpillar.pk }}", name: "{{ subpillar.name|escapejs }}", },
            {% endfor %}
        ],
    },
    {% endfor %}
];

var sectors = [
    {% for sector in sectors %}
    {
        id: "{{ sector.pk }}",
        name: "{{ sector.name|escapejs }}",
        {% comment %}
        subsectors: [
            {% for subsector in sector.subsector_set.all %}
            { id: "{{ subsector.pk }}", name: "{{ subsector.name|escapejs }}", },
            {% endfor %}
        ],
        {% endcomment %}
    },
    {% endfor %}
];
</script>

{% endblock %}

{% block body %}

{% include 'navbar.html' %}

<aside id="preview-section">
    <div>No preview available</div>
    <iframe src="about:blank" hidden></iframe>
</aside>

<main>
    <section id="entries-export">
        <div>
            <form id="export-entries-doc-form" action="{% url 'entries:exportdoc' event=event.pk %}" method="post">
                <header>
                    <div class="export-format">
                        <label class="active"><input type="radio" name="export-format" value="generic" checked> Generic</label>
                        <label><input type="radio" name="export-format" value="geo"> Geo</label>
                        <label><input type="radio" name="export-format" value="briefing"> Briefing note</label>
                    </div>
                    <div class="action-buttons">
                        <div class="preview-buttons">
                            <button class="btn-word" id="preview-docx" type="button"><i class="fa fa-file-word-o"></i>Preview docx</button>
                        </div>
                        <div class="export-buttons">
                            <button class="btn-pdf" id="export-pdf" type="button"><i class="fa fa-file-pdf-o"></i>Export pdf</button>
                            <button class="btn-word" id="export-docx" type="button"><i class="fa fa-file-word-o"></i>Export docx</button>
                            <button class="btn-excel" type="button" id="export-xlsx"><i class="fa fa-file-excel-o"></i>Export xlsx</button>
                            <button class="btn-json export-button" type="button" data-url="{% url 'api_entries:entries' %}?event={{event.pk}}&file=1"><i class="fa fa-file-text-o"></i>Export json</button>
                        </div>
                    </div>
                </header>

                <div id="filter-section">
                    <h4>Filters</h4>
                    <div class="filters">
                        {% include 'entries/export-entry-filters.html' %}
                        <div class="filter-group" id="leads-selection">
                            <header >
                                <h5 onclick="$(this).closest('.filter-group').toggleClass('filters-shown').find('.filters-container').slideToggle('200')"><label>Leads: <span id='selected-leads-count'></span></label><i class="fa fa-chevron-down"></i></h5>
                            </header>
                            <div class="filters-container" hidden>
                                {% include 'entries/export-leads.html' %}
                            </div>
                        </div>
                        <div class="filter-group" id="lead-published-order">
                            <h5>Leads published date order</h5>

                            <div class="radio-group">
                                <label><input name="order_by" value="DATE_DESCENDING" type="radio" checked="checked">Most recent to ancient</label>
                                <label><input name="order_by" value="DATE_ASCENDING" type="radio">Ancient to most recent</label>
                            </div>
                        </div>
                    </div>

                </div>

                <div id="structure-section">
                    <h4>Report Structure</h4>

                    <input id="list-order" name="list-order" value="" type="hidden">
                    <div class="check-group-list">
                    </div>

                    <div class="check-template" hidden><label><input type="checkbox"><span class="name"></span><span class="number"></span></label></div>
                    <div class="check-group-template expandable" hidden>
                        <header class="check"><label><input type="checkbox"><span class="name"></span><span class="number"></span></label><a class="fa fa-chevron-down check-group-expand"></a></header>
                        <div class="content" hidden></div>
                        <input class="group-order" type="hidden">
                    </div>
                </div>

            </form>
        </div>
    </section>
    <!--
    <section>
    <h2>Assessment Registry</h2>
    <div class="content">
    <button class="btn-excel export-button" data-url="{% url 'leads:exportsosxls' event=event.pk %}"><i class="fa fa-file-excel-o"></i>Export xlsx</button>
    <button class="btn-json export-button" data-url="{% url 'api_leads:sos' %}?event={{event.pk}}&file=1"><i class="fa fa-file-text-o"></i>Export json</button>
</div>
</section>
<section>
<h2>Weekly snapshot</h2>
<div class="content">
<button class="btn-excel export-button" data-url="{% url 'entries:exportxls_weekly' event=event.pk %}"><i class="fa fa-file-excel-o"></i>Export xlsx</button>
<button class="btn-json export-button" data-url="{% url 'api_report:reports' %}?event={{event.pk}}&file=1"><i class="fa fa-file-text-o"></i>Export json</button>
</div>
</section>
-->
</main>

<div class="modal-container" hidden>
    <div id="date-range-input" class="modal" hidden>
        <header>
            <h3 class="modal-title">Enter date range</h3>
        </header>
        <div class="input-container">
            <label>start date:</label>
            <input type="date" id="start-date" class="form-control">
            <input type="text" class="date-picker" data-alt="#start-date">
        </div>
        <div class="input-container">
            <label>end date:</label>
            <input type="date" id="end-date" class="form-control">
            <input type="text" class="date-picker" data-alt="#end-date">
        </div>
        <div class="action-buttons">
            <button id="cancel-btn" class="cancel" data-action="dismiss"><i class="fa fa-times"></i>Cancel</button>
            <button id="ok-btn" class="success" data-action="proceed"><i class="fa fa-check"></i>Ok</button>
        </div>
    </div>

    {% endblock %}